version: '3.8'

services:
  cellular-bridge:
    build: .
    container_name: cellular-bridge
    ports:
      - "8080:8000"
#    devices:
      # Map the Raspberry Pi physical UART serial port to the container
#      - "/dev/ttyAMA0:/dev/ttyAMA0"
    security_opt:
      # Some Linux systems require raw peripheral access flags
      - apparmor:unconfined
    environment:
      - CELLULAR_BRIDGE_API_KEY=${CELLULAR_BRIDGE_API_KEY:-}
    volumes:
      - ./data:/app/data
    restart: always
